name = "SneakerStudio Upsell"
client_id = "892ad7f6e534355d73d719df764c2005"
application_url = "https://ss-upsell.vercel.app/api/auth"
embedded = false

[access_scopes]
scopes = "read_products,read_orders"

[auth]
redirect_urls = [ "https://ss-upsell.vercel.app/api/callback" ]

[webhooks]
api_version = "2025-07"

[build]
